name: swustmctown
version: '${project.version}'
main: org.swustmc.Swustmctown
api-version: '1.20'

softdepend: [PlaceholderAPI]

commands:
  swustmctown:
    description: SWUSTMCTown 插件的主命令
    usage: /<command>

permissions:
  swustmctown.admin:
    description: Admin commands access.
    default: op